### ISSUE TITLE
Some input files use or override a deprecated API.

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-plugin-firebase#6]
```
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /home/itee/Mobile/soccer/build/cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:6: error: cannot find symbol
import com.eclipsesource.tabris.android.AbstractOperator;
                                       ^
  symbol:   class AbstractOperator
  location: package com.eclipsesource.tabris.android
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:7: error: cannot find symbol
import com.eclipsesource.tabris.android.Properties;
                                       ^
  symbol:   class Properties
  location: package com.eclipsesource.tabris.android
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:8: error: cannot find symbol
import com.eclipsesource.tabris.android.PropertyHandler;
                                       ^
  symbol:   class PropertyHandler
  location: package com.eclipsesource.tabris.android
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:11: error: cannot find symbol
public class MessagingOperator extends AbstractOperator<Messaging> {
                                       ^
  symbol: class AbstractOperator
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/Messaging.java:11: error: cannot find symbol
import com.eclipsesource.tabris.android.RemoteObject;
                                       ^
  symbol:   class RemoteObject
  location: package com.eclipsesource.tabris.android
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingPropertyHandler.java:4: error: cannot find symbol
import com.eclipsesource.tabris.android.Properties;
                                       ^
  symbol:   class Properties
  location: package com.eclipsesource.tabris.android
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingPropertyHandler.java:5: error: cannot find symbol
import com.eclipsesource.tabris.android.PropertyHandler;
                                       ^
  symbol:   class PropertyHandler
  location: package com.eclipsesource.tabris.android
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingPropertyHandler.java:8: error: cannot find symbol
class MessagingPropertyHandler implements PropertyHandler<Messaging> {
                                          ^
  symbol: class PropertyHandler
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:27: error: cannot find symbol
  public PropertyHandler<Messaging> getPropertyHandler( Messaging messaging ) {
         ^
  symbol:   class PropertyHandler
  location: class MessagingOperator
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:37: error: cannot find symbol
  public Messaging create( String id, Properties properties ) {
                                      ^
  symbol:   class Properties
  location: class MessagingOperator
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:42: error: cannot find symbol
  public Object call( Messaging messaging, String method, Properties properties ) {
                                                          ^
  symbol:   class Properties
  location: class MessagingOperator
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingPropertyHandler.java:28: error: cannot find symbol
  public void set( Messaging messaging, Properties properties ) {
                                        ^
  symbol:   class Properties
  location: class MessagingPropertyHandler
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:26: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:31: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:36: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:41: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingOperator.java:49: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/Messaging.java:112: error: cannot find symbol
              RemoteObject remoteObject = tabrisContext.getObjectRegistry().getRemoteObjectForObject( Messaging.this );
              ^
  symbol: class RemoteObject
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingPropertyHandler.java:14: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/itee/Mobile/soccer/build/cordova/platforms/android/src/com/eclipsesource/firebase/messaging/MessagingPropertyHandler.java:27: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: /home/itee/Mobile/soccer/build/cordova/platforms/android/src/nl/xservices/plugins/SocialSharing.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
20 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
/usr/local/lib/node_modules/tabris-cli/src/build.js:86
    throw new Error(`The command ${cmd} exited with ${ps.status}`);
    ^

Error: The command cordova exited with 1
    at exec (/usr/local/lib/node_modules/tabris-cli/src/build.js:86:11)
    at runCordovaBuild (/usr/local/lib/node_modules/tabris-cli/src/build.js:62:3)
    at build (/usr/local/lib/node_modules/tabris-cli/src/build.js:38:3)
    at Command.program.command.description.action.platform (/usr/local/lib/node_modules/tabris-cli/src/build.js:12:23)
    at Command.listener (/usr/local/lib/node_modules/tabris-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/tabris-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/tabris-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/tabris-cli/src/tabris.js:10:9)

```

**Comment by mpost** [comment]
The plugins _master_ branch is compatible with Tabris.js 2.0 _master_ branch so you have to use a nightly version of Tabris.js 2.0 or use an older commit of the `tabris-plugin-firebase`.

**Comment by mpost** [comment]
Closing as resolved. Please reopen if you have any more problems.
